name: latana
description: "Assessment for flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  stacked: ^3.4.3
  stacked_services: ^1.5.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  stacked_generator: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
